### ISSUE TITLE
Unable to submit new location. Error: One or more parameter values are not valid. A value specified for a secondary index key is not supported. The AttributeValue for a key attribute cannot contain an empty string value. IndexName: GSI2, IndexKey: GSI2

### ISSUE THREAD

**Issue by adampann** [International-Slackline-Association/slackmap#10]
Just signed up for slackmap and am trying to submit a new location. However it fails to submit.

<img width="1589" alt="image" src="https://user-images.githubusercontent.com/25598414/235573177-1933cb11-d76d-4418-9651-117e51a8704f.png">

<img width="461" alt="image" src="https://user-images.githubusercontent.com/25598414/235573353-f8ad31ee-4e56-4e02-b36d-fe554227d5e8.png">

**Comment by Can-Sahin** [comment]
Hey thanks alot. I did a mistake 2 days ago and fixed it now. Easy mistake :)

**Comment by Can-Sahin** [comment]
Let me know if still goes on though (I checked it now)
