### ISSUE TITLE
The Sign In / Sign up button does not work  - Impossible to sign in

### ISSUE THREAD

**Issue by GaelleJoubert** [International-Slackline-Association/slackmap#11]
When clicking oon the button : 
- the "splash" effect works
- nothing else happen

I tried on different web browser : 
- Mozilla (windows computer) -> with all the add block disabled
- Chrome (windows computer)
- Chrome (Pixel 6a smartphone)
- Firefox (Pixel 6a smartphone)

I have the same behavior each time.

I also tried the button from the burger menu, or from the pop up when trying to "add a new line", and both does not work.

**Comment by Can-Sahin** [comment]
Hmm I dont understand what it could be. You need to look at the console errors described [here](https://documentation.concretecms.org/tutorials/how-open-browser-console-view-errors). Its very simple. And it can tell whats wrong. If you share it with me I can look. Otherwise its impossible for me to figure out :(

**Comment by GaelleJoubert** [comment]
So I tried it again, and It still does not work. 
Here is the issue I have in  the console : 

![image](https://github.com/user-attachments/assets/74271ca6-440d-4e70-98fd-355720f89492)

If I unfold the error on "post" :

Request Header : 

HTTP/1.1 400 Bad Request
x-amzn-RequestId: 2aba61c0-c3e0-4599-aa63-252509d3efc6
Access-Control-Allow-Origin: *
x-amzn-ErrorType: ValidationException:http://internal.amazon.com/coral/com.amazon.coral.validate/
Access-Control-Expose-Headers: x-amzn-RequestId,x-amzn-ErrorType,x-amzn-ErrorMessage,Date
Content-Type: application/json
Content-Length: 64
Date: Mon, 16 Sep 2024 09:26:34 GMT
Connection: close

Request Header :

**Comment by rorystephenson** [comment]
Maybe this: https://github.com/aws-amplify/amplify-js/issues/12871#issuecomment-1906502576

**Comment by Can-Sahin** [comment]
Yeah i told tom its www used. Will look into it later to get rid of this www forever. It cause problem so many times

**Comment by Can-Sahin** [comment]
Ok fixed it. Should work for both. Thanks for pointing it out. Would have never realized myself
